# Site settings

title: 江南易的技术博客
email: yanqibo123@outlook.com
description: > #江南易的技术博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://asiay.asia" # the base hostname & protocol for your site

# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

twitter_username: CurtisYan
github_username:  CurtisYan

# Build settings

#markdown: kramdown
permalink: /:year/:month/:day/:title.html   #博文的固定链接
paginate: 10                                #分页时每页博文数量
author:                                     #自定义常亮
  name: 江南易
  email: yanqibo123@outlook.com
  link: http://asiay.asia
  github: https://github.com/CurtisYan
  twitte:
title: 江南易的技术博客                             #自定义常量

# avatar头像及Favicon
avatar:  https://curtisyan.oss-cn-shenzhen.aliyuncs.com/img/no_important/202406032300481.jpg
favicon: https://curtisyan.oss-cn-shenzhen.aliyuncs.com/img/no_important/202406032349614.png

locals:                                     #自定义常量
  tags: 标签
  about: 关于
active: 技术                                 #自定义常量
subscribe_rss: /pages/atom.xml              #订阅地址
markdown: kramdown                         #markdown解释器

# google analytics 设置
#ga:
#  id:
#  url:

#

# baidu analytics 设置

ba:
  src: //hm.baidu.com/hm.js?22d94317cfb9f9e0bb476228d9f79278

# disqus 设置
disqus:
  shortname: 江南易

